# Generated by Django 5.1.2 on 2024-10-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('programsdir', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programas',
            new_name='Programs',
        ),
    ]
